// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exchange.proto

package x

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order_OrderSide int32

const (
	Order_Buy  Order_OrderSide = 0
	Order_Sell Order_OrderSide = 1
)

var Order_OrderSide_name = map[int32]string{
	0: "Buy",
	1: "Sell",
}

var Order_OrderSide_value = map[string]int32{
	"Buy":  0,
	"Sell": 1,
}

func (x Order_OrderSide) String() string {
	return proto.EnumName(Order_OrderSide_name, int32(x))
}

func (Order_OrderSide) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{5, 0}
}

type Order_TimeInForce int32

const (
	Order_GTC Order_TimeInForce = 0
	Order_GTT Order_TimeInForce = 1
	Order_IOC Order_TimeInForce = 2
	Order_FOK Order_TimeInForce = 3
)

var Order_TimeInForce_name = map[int32]string{
	0: "GTC",
	1: "GTT",
	2: "IOC",
	3: "FOK",
}

var Order_TimeInForce_value = map[string]int32{
	"GTC": 0,
	"GTT": 1,
	"IOC": 2,
	"FOK": 3,
}

func (x Order_TimeInForce) String() string {
	return proto.EnumName(Order_TimeInForce_name, int32(x))
}

func (Order_TimeInForce) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{5, 1}
}

type Order_OrderType int32

const (
	Order_LIMIT             Order_OrderType = 0
	Order_MARKET            Order_OrderType = 1
	Order_STOP_LOSS         Order_OrderType = 2
	Order_STOP_LOSS_LIMIT   Order_OrderType = 3
	Order_TAKE_PROFIT       Order_OrderType = 4
	Order_TAKE_PROFIT_LIMIT Order_OrderType = 5
	Order_LIMIT_MAKER       Order_OrderType = 6
)

var Order_OrderType_name = map[int32]string{
	0: "LIMIT",
	1: "MARKET",
	2: "STOP_LOSS",
	3: "STOP_LOSS_LIMIT",
	4: "TAKE_PROFIT",
	5: "TAKE_PROFIT_LIMIT",
	6: "LIMIT_MAKER",
}

var Order_OrderType_value = map[string]int32{
	"LIMIT":             0,
	"MARKET":            1,
	"STOP_LOSS":         2,
	"STOP_LOSS_LIMIT":   3,
	"TAKE_PROFIT":       4,
	"TAKE_PROFIT_LIMIT": 5,
	"LIMIT_MAKER":       6,
}

func (x Order_OrderType) String() string {
	return proto.EnumName(Order_OrderType_name, int32(x))
}

func (Order_OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{5, 2}
}

type Trade_Maker int32

const (
	Trade_Unknown Trade_Maker = 0
	Trade_Buyer   Trade_Maker = 1
	Trade_Seller  Trade_Maker = 2
)

var Trade_Maker_name = map[int32]string{
	0: "Unknown",
	1: "Buyer",
	2: "Seller",
}

var Trade_Maker_value = map[string]int32{
	"Unknown": 0,
	"Buyer":   1,
	"Seller":  2,
}

func (x Trade_Maker) String() string {
	return proto.EnumName(Trade_Maker_name, int32(x))
}

func (Trade_Maker) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{10, 0}
}

type Frequency struct {
	Nanos                int64    `protobuf:"varint,1,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Frequency) Reset()         { *m = Frequency{} }
func (m *Frequency) String() string { return proto.CompactTextString(m) }
func (*Frequency) ProtoMessage()    {}
func (*Frequency) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{0}
}

func (m *Frequency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frequency.Unmarshal(m, b)
}
func (m *Frequency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frequency.Marshal(b, m, deterministic)
}
func (m *Frequency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frequency.Merge(m, src)
}
func (m *Frequency) XXX_Size() int {
	return xxx_messageInfo_Frequency.Size(m)
}
func (m *Frequency) XXX_DiscardUnknown() {
	xxx_messageInfo_Frequency.DiscardUnknown(m)
}

var xxx_messageInfo_Frequency proto.InternalMessageInfo

func (m *Frequency) GetNanos() int64 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

type Balance struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Asset                string   `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Available            float64  `protobuf:"fixed64,3,opt,name=available,proto3" json:"available,omitempty"`
	Locked               float64  `protobuf:"fixed64,5,opt,name=locked,proto3" json:"locked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{1}
}

func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Balance) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *Balance) GetAvailable() float64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *Balance) GetLocked() float64 {
	if m != nil {
		return m.Locked
	}
	return 0
}

type AccountQuery struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountQuery) Reset()         { *m = AccountQuery{} }
func (m *AccountQuery) String() string { return proto.CompactTextString(m) }
func (*AccountQuery) ProtoMessage()    {}
func (*AccountQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{2}
}

func (m *AccountQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountQuery.Unmarshal(m, b)
}
func (m *AccountQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountQuery.Marshal(b, m, deterministic)
}
func (m *AccountQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountQuery.Merge(m, src)
}
func (m *AccountQuery) XXX_Size() int {
	return xxx_messageInfo_AccountQuery.Size(m)
}
func (m *AccountQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountQuery.DiscardUnknown(m)
}

var xxx_messageInfo_AccountQuery proto.InternalMessageInfo

type StreamAccountQuery struct {
	Query                *AccountQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Frequency            *Frequency    `protobuf:"bytes,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StreamAccountQuery) Reset()         { *m = StreamAccountQuery{} }
func (m *StreamAccountQuery) String() string { return proto.CompactTextString(m) }
func (*StreamAccountQuery) ProtoMessage()    {}
func (*StreamAccountQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{3}
}

func (m *StreamAccountQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamAccountQuery.Unmarshal(m, b)
}
func (m *StreamAccountQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamAccountQuery.Marshal(b, m, deterministic)
}
func (m *StreamAccountQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamAccountQuery.Merge(m, src)
}
func (m *StreamAccountQuery) XXX_Size() int {
	return xxx_messageInfo_StreamAccountQuery.Size(m)
}
func (m *StreamAccountQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamAccountQuery.DiscardUnknown(m)
}

var xxx_messageInfo_StreamAccountQuery proto.InternalMessageInfo

func (m *StreamAccountQuery) GetQuery() *AccountQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *StreamAccountQuery) GetFrequency() *Frequency {
	if m != nil {
		return m.Frequency
	}
	return nil
}

type Account struct {
	Balances             map[string]*Balance `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Tradeable            bool                `protobuf:"varint,2,opt,name=tradeable,proto3" json:"tradeable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{4}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetBalances() map[string]*Balance {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *Account) GetTradeable() bool {
	if m != nil {
		return m.Tradeable
	}
	return false
}

type Order struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                float64           `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             float64           `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Side                 Order_OrderSide   `protobuf:"varint,4,opt,name=side,proto3,enum=x.Order_OrderSide" json:"side,omitempty"`
	Pair                 string            `protobuf:"bytes,5,opt,name=pair,proto3" json:"pair,omitempty"`
	TimeInForce          Order_TimeInForce `protobuf:"varint,6,opt,name=timeInForce,proto3,enum=x.Order_TimeInForce" json:"timeInForce,omitempty"`
	OrderType            Order_OrderType   `protobuf:"varint,7,opt,name=order_type,json=orderType,proto3,enum=x.Order_OrderType" json:"order_type,omitempty"`
	CancelAfter          uint32            `protobuf:"varint,8,opt,name=cancel_after,json=cancelAfter,proto3" json:"cancel_after,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{5}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetQuantity() float64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Order) GetSide() Order_OrderSide {
	if m != nil {
		return m.Side
	}
	return Order_Buy
}

func (m *Order) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *Order) GetTimeInForce() Order_TimeInForce {
	if m != nil {
		return m.TimeInForce
	}
	return Order_GTC
}

func (m *Order) GetOrderType() Order_OrderType {
	if m != nil {
		return m.OrderType
	}
	return Order_LIMIT
}

func (m *Order) GetCancelAfter() uint32 {
	if m != nil {
		return m.CancelAfter
	}
	return 0
}

type OrderStatus struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Trades               []*Trade `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderStatus) Reset()         { *m = OrderStatus{} }
func (m *OrderStatus) String() string { return proto.CompactTextString(m) }
func (*OrderStatus) ProtoMessage()    {}
func (*OrderStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{6}
}

func (m *OrderStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderStatus.Unmarshal(m, b)
}
func (m *OrderStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderStatus.Marshal(b, m, deterministic)
}
func (m *OrderStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderStatus.Merge(m, src)
}
func (m *OrderStatus) XXX_Size() int {
	return xxx_messageInfo_OrderStatus.Size(m)
}
func (m *OrderStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderStatus.DiscardUnknown(m)
}

var xxx_messageInfo_OrderStatus proto.InternalMessageInfo

func (m *OrderStatus) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderStatus) GetTrades() []*Trade {
	if m != nil {
		return m.Trades
	}
	return nil
}

func (m *OrderStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type TradeQuery struct {
	Pair                 string   `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeQuery) Reset()         { *m = TradeQuery{} }
func (m *TradeQuery) String() string { return proto.CompactTextString(m) }
func (*TradeQuery) ProtoMessage()    {}
func (*TradeQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{7}
}

func (m *TradeQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeQuery.Unmarshal(m, b)
}
func (m *TradeQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeQuery.Marshal(b, m, deterministic)
}
func (m *TradeQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeQuery.Merge(m, src)
}
func (m *TradeQuery) XXX_Size() int {
	return xxx_messageInfo_TradeQuery.Size(m)
}
func (m *TradeQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeQuery.DiscardUnknown(m)
}

var xxx_messageInfo_TradeQuery proto.InternalMessageInfo

func (m *TradeQuery) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

type TradesQuery struct {
	Pair                 string   `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradesQuery) Reset()         { *m = TradesQuery{} }
func (m *TradesQuery) String() string { return proto.CompactTextString(m) }
func (*TradesQuery) ProtoMessage()    {}
func (*TradesQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{8}
}

func (m *TradesQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradesQuery.Unmarshal(m, b)
}
func (m *TradesQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradesQuery.Marshal(b, m, deterministic)
}
func (m *TradesQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradesQuery.Merge(m, src)
}
func (m *TradesQuery) XXX_Size() int {
	return xxx_messageInfo_TradesQuery.Size(m)
}
func (m *TradesQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_TradesQuery.DiscardUnknown(m)
}

var xxx_messageInfo_TradesQuery proto.InternalMessageInfo

func (m *TradesQuery) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *TradesQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type StreamTradeQuery struct {
	Query                *TradeQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Frequency            *Frequency  `protobuf:"bytes,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StreamTradeQuery) Reset()         { *m = StreamTradeQuery{} }
func (m *StreamTradeQuery) String() string { return proto.CompactTextString(m) }
func (*StreamTradeQuery) ProtoMessage()    {}
func (*StreamTradeQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{9}
}

func (m *StreamTradeQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamTradeQuery.Unmarshal(m, b)
}
func (m *StreamTradeQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamTradeQuery.Marshal(b, m, deterministic)
}
func (m *StreamTradeQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamTradeQuery.Merge(m, src)
}
func (m *StreamTradeQuery) XXX_Size() int {
	return xxx_messageInfo_StreamTradeQuery.Size(m)
}
func (m *StreamTradeQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamTradeQuery.DiscardUnknown(m)
}

var xxx_messageInfo_StreamTradeQuery proto.InternalMessageInfo

func (m *StreamTradeQuery) GetQuery() *TradeQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *StreamTradeQuery) GetFrequency() *Frequency {
	if m != nil {
		return m.Frequency
	}
	return nil
}

type Trade struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Maker                Trade_Maker `protobuf:"varint,2,opt,name=maker,proto3,enum=x.Trade_Maker" json:"maker,omitempty"`
	Price                float64     `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             float64     `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Pair                 string      `protobuf:"bytes,5,opt,name=pair,proto3" json:"pair,omitempty"`
	CreatedAt            *Timestamp  `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{10}
}

func (m *Trade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trade.Unmarshal(m, b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
}
func (m *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(m, src)
}
func (m *Trade) XXX_Size() int {
	return xxx_messageInfo_Trade.Size(m)
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Trade) GetMaker() Trade_Maker {
	if m != nil {
		return m.Maker
	}
	return Trade_Unknown
}

func (m *Trade) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trade) GetQuantity() float64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Trade) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *Trade) GetCreatedAt() *Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Trades struct {
	Trades               []*Trade `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trades) Reset()         { *m = Trades{} }
func (m *Trades) String() string { return proto.CompactTextString(m) }
func (*Trades) ProtoMessage()    {}
func (*Trades) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{11}
}

func (m *Trades) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trades.Unmarshal(m, b)
}
func (m *Trades) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trades.Marshal(b, m, deterministic)
}
func (m *Trades) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trades.Merge(m, src)
}
func (m *Trades) XXX_Size() int {
	return xxx_messageInfo_Trades.Size(m)
}
func (m *Trades) XXX_DiscardUnknown() {
	xxx_messageInfo_Trades.DiscardUnknown(m)
}

var xxx_messageInfo_Trades proto.InternalMessageInfo

func (m *Trades) GetTrades() []*Trade {
	if m != nil {
		return m.Trades
	}
	return nil
}

type QuoteQuery struct {
	Pair                 string   `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuoteQuery) Reset()         { *m = QuoteQuery{} }
func (m *QuoteQuery) String() string { return proto.CompactTextString(m) }
func (*QuoteQuery) ProtoMessage()    {}
func (*QuoteQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{12}
}

func (m *QuoteQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuoteQuery.Unmarshal(m, b)
}
func (m *QuoteQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuoteQuery.Marshal(b, m, deterministic)
}
func (m *QuoteQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuoteQuery.Merge(m, src)
}
func (m *QuoteQuery) XXX_Size() int {
	return xxx_messageInfo_QuoteQuery.Size(m)
}
func (m *QuoteQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_QuoteQuery.DiscardUnknown(m)
}

var xxx_messageInfo_QuoteQuery proto.InternalMessageInfo

func (m *QuoteQuery) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

type StreamQuoteQuery struct {
	Query                *QuoteQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Frequency            *Frequency  `protobuf:"bytes,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StreamQuoteQuery) Reset()         { *m = StreamQuoteQuery{} }
func (m *StreamQuoteQuery) String() string { return proto.CompactTextString(m) }
func (*StreamQuoteQuery) ProtoMessage()    {}
func (*StreamQuoteQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{13}
}

func (m *StreamQuoteQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamQuoteQuery.Unmarshal(m, b)
}
func (m *StreamQuoteQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamQuoteQuery.Marshal(b, m, deterministic)
}
func (m *StreamQuoteQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamQuoteQuery.Merge(m, src)
}
func (m *StreamQuoteQuery) XXX_Size() int {
	return xxx_messageInfo_StreamQuoteQuery.Size(m)
}
func (m *StreamQuoteQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamQuoteQuery.DiscardUnknown(m)
}

var xxx_messageInfo_StreamQuoteQuery proto.InternalMessageInfo

func (m *StreamQuoteQuery) GetQuery() *QuoteQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *StreamQuoteQuery) GetFrequency() *Frequency {
	if m != nil {
		return m.Frequency
	}
	return nil
}

type Quote struct {
	AskPrice             float64    `protobuf:"fixed64,1,opt,name=askPrice,proto3" json:"askPrice,omitempty"`
	AskQuantity          float64    `protobuf:"fixed64,2,opt,name=ask_quantity,json=askQuantity,proto3" json:"ask_quantity,omitempty"`
	BidPrice             float64    `protobuf:"fixed64,3,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	BidQuantity          float64    `protobuf:"fixed64,4,opt,name=bid_quantity,json=bidQuantity,proto3" json:"bid_quantity,omitempty"`
	Pair                 string     `protobuf:"bytes,5,opt,name=pair,proto3" json:"pair,omitempty"`
	CreatedAt            *Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Quote) Reset()         { *m = Quote{} }
func (m *Quote) String() string { return proto.CompactTextString(m) }
func (*Quote) ProtoMessage()    {}
func (*Quote) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{14}
}

func (m *Quote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quote.Unmarshal(m, b)
}
func (m *Quote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quote.Marshal(b, m, deterministic)
}
func (m *Quote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quote.Merge(m, src)
}
func (m *Quote) XXX_Size() int {
	return xxx_messageInfo_Quote.Size(m)
}
func (m *Quote) XXX_DiscardUnknown() {
	xxx_messageInfo_Quote.DiscardUnknown(m)
}

var xxx_messageInfo_Quote proto.InternalMessageInfo

func (m *Quote) GetAskPrice() float64 {
	if m != nil {
		return m.AskPrice
	}
	return 0
}

func (m *Quote) GetAskQuantity() float64 {
	if m != nil {
		return m.AskQuantity
	}
	return 0
}

func (m *Quote) GetBidPrice() float64 {
	if m != nil {
		return m.BidPrice
	}
	return 0
}

func (m *Quote) GetBidQuantity() float64 {
	if m != nil {
		return m.BidQuantity
	}
	return 0
}

func (m *Quote) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *Quote) GetCreatedAt() *Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type Timestamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos                int64    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0328a4f16f87ea1, []int{15}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanos() int64 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

func init() {
	proto.RegisterEnum("x.Order_OrderSide", Order_OrderSide_name, Order_OrderSide_value)
	proto.RegisterEnum("x.Order_TimeInForce", Order_TimeInForce_name, Order_TimeInForce_value)
	proto.RegisterEnum("x.Order_OrderType", Order_OrderType_name, Order_OrderType_value)
	proto.RegisterEnum("x.Trade_Maker", Trade_Maker_name, Trade_Maker_value)
	proto.RegisterType((*Frequency)(nil), "x.Frequency")
	proto.RegisterType((*Balance)(nil), "x.Balance")
	proto.RegisterType((*AccountQuery)(nil), "x.AccountQuery")
	proto.RegisterType((*StreamAccountQuery)(nil), "x.StreamAccountQuery")
	proto.RegisterType((*Account)(nil), "x.Account")
	proto.RegisterMapType((map[string]*Balance)(nil), "x.Account.BalancesEntry")
	proto.RegisterType((*Order)(nil), "x.Order")
	proto.RegisterType((*OrderStatus)(nil), "x.OrderStatus")
	proto.RegisterType((*TradeQuery)(nil), "x.TradeQuery")
	proto.RegisterType((*TradesQuery)(nil), "x.TradesQuery")
	proto.RegisterType((*StreamTradeQuery)(nil), "x.StreamTradeQuery")
	proto.RegisterType((*Trade)(nil), "x.Trade")
	proto.RegisterType((*Trades)(nil), "x.Trades")
	proto.RegisterType((*QuoteQuery)(nil), "x.QuoteQuery")
	proto.RegisterType((*StreamQuoteQuery)(nil), "x.StreamQuoteQuery")
	proto.RegisterType((*Quote)(nil), "x.Quote")
	proto.RegisterType((*Timestamp)(nil), "x.Timestamp")
}

func init() { proto.RegisterFile("exchange.proto", fileDescriptor_e0328a4f16f87ea1) }

var fileDescriptor_e0328a4f16f87ea1 = []byte{
	// 984 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0xf6, 0x92, 0xa2, 0x44, 0x0e, 0x6d, 0x99, 0xdd, 0x24, 0x05, 0xa1, 0x16, 0x85, 0xc2, 0xa4,
	0x81, 0xea, 0x00, 0xac, 0xa3, 0x06, 0x6d, 0xd1, 0x9e, 0xe4, 0xc0, 0x36, 0x04, 0xc7, 0x90, 0xbd,
	0x52, 0xcf, 0xc2, 0x8a, 0xdc, 0xa4, 0x84, 0x64, 0x52, 0x26, 0x97, 0xa9, 0x74, 0xea, 0xdb, 0xf4,
	0x55, 0xfa, 0x14, 0x3d, 0xf7, 0xd2, 0x87, 0x28, 0x76, 0x97, 0x7f, 0x76, 0xe4, 0x1e, 0x82, 0x5e,
	0x84, 0xf9, 0xdb, 0xd9, 0xd9, 0xf9, 0xe6, 0xe3, 0x08, 0xba, 0x6c, 0x13, 0xfc, 0x4a, 0xe3, 0xf7,
	0xcc, 0x5f, 0xa7, 0x09, 0x4f, 0x30, 0xda, 0x78, 0x4f, 0xc1, 0x3a, 0x4b, 0xd9, 0x6d, 0xce, 0xe2,
	0x60, 0x8b, 0x1f, 0x83, 0x11, 0xd3, 0x38, 0xc9, 0x5c, 0xd4, 0x47, 0x03, 0x9d, 0x28, 0xc5, 0x63,
	0xd0, 0x39, 0xa1, 0x2b, 0x1a, 0x07, 0x0c, 0x77, 0x41, 0x8b, 0x42, 0xe9, 0xb5, 0x88, 0x16, 0x85,
	0xe2, 0x00, 0xcd, 0x32, 0xc6, 0x5d, 0x4d, 0x9a, 0x94, 0x82, 0xbf, 0x04, 0x8b, 0x7e, 0xa0, 0xd1,
	0x8a, 0x2e, 0x56, 0xcc, 0xd5, 0xfb, 0x68, 0x80, 0x48, 0x6d, 0xc0, 0x9f, 0x43, 0x7b, 0x95, 0x04,
	0x4b, 0x16, 0xba, 0x86, 0x74, 0x15, 0x9a, 0xd7, 0x85, 0xfd, 0x51, 0x10, 0x24, 0x79, 0xcc, 0xaf,
	0x73, 0x96, 0x6e, 0xbd, 0xf7, 0x80, 0xa7, 0x3c, 0x65, 0xf4, 0xa6, 0x69, 0xc5, 0x5f, 0x83, 0x71,
	0x2b, 0x04, 0x59, 0x84, 0x3d, 0x3c, 0xf4, 0x37, 0x7e, 0xd3, 0x4f, 0x94, 0x17, 0x1f, 0x81, 0xf5,
	0xae, 0x7c, 0x96, 0x2c, 0xce, 0x1e, 0xee, 0xfb, 0x1b, 0xbf, 0x7a, 0x2a, 0xa9, 0xdd, 0xde, 0x1f,
	0x08, 0x3a, 0x45, 0x0e, 0xfc, 0x1a, 0xcc, 0x85, 0x7a, 0xab, 0x68, 0x82, 0x3e, 0xb0, 0x87, 0x6e,
	0x7d, 0x83, 0x5f, 0xb4, 0x21, 0x3b, 0x8d, 0x79, 0xba, 0x25, 0x55, 0xa4, 0x78, 0x30, 0x4f, 0x69,
	0xc8, 0xe4, 0x83, 0xc5, 0x6d, 0x26, 0xa9, 0x0d, 0xbd, 0x73, 0x38, 0xb8, 0x73, 0x10, 0x3b, 0xa0,
	0x2f, 0xd9, 0xb6, 0x68, 0xa3, 0x10, 0x71, 0x1f, 0x8c, 0x0f, 0x74, 0x95, 0xb3, 0xa2, 0x54, 0xf0,
	0x37, 0xe5, 0x5d, 0x44, 0x39, 0x7e, 0xd2, 0x7e, 0x44, 0xde, 0xdf, 0x3a, 0x18, 0x93, 0x34, 0x64,
	0xe9, 0x2e, 0x1c, 0xd6, 0x69, 0x14, 0xa8, 0xf3, 0x88, 0x28, 0x05, 0xf7, 0xc0, 0xbc, 0xcd, 0x69,
	0xcc, 0x23, 0xbe, 0x2d, 0x60, 0xa8, 0x74, 0xfc, 0x02, 0x5a, 0x59, 0x14, 0x32, 0xb7, 0xd5, 0x47,
	0x83, 0xee, 0x10, 0xfb, 0x1b, 0x5f, 0x66, 0x56, 0xbf, 0xd3, 0x28, 0x64, 0x44, 0xfa, 0x31, 0x86,
	0xd6, 0x9a, 0x46, 0xa9, 0xc4, 0xca, 0x22, 0x52, 0xc6, 0xdf, 0x83, 0xcd, 0xa3, 0x1b, 0x36, 0x8e,
	0xcf, 0x92, 0x34, 0x60, 0x6e, 0x5b, 0xa6, 0x78, 0x5c, 0xa5, 0x98, 0xd5, 0x3e, 0xd2, 0x0c, 0xc4,
	0xaf, 0x00, 0x12, 0x11, 0x31, 0xe7, 0xdb, 0x35, 0x73, 0x3b, 0xbb, 0x6e, 0x9e, 0x6d, 0xd7, 0x8c,
	0x58, 0x49, 0x29, 0xe2, 0xa7, 0xb0, 0x1f, 0x88, 0x36, 0xac, 0xe6, 0xf4, 0x1d, 0x67, 0xa9, 0x6b,
	0xf6, 0xd1, 0xe0, 0x80, 0xd8, 0xca, 0x36, 0x12, 0x26, 0xef, 0x2b, 0xb0, 0xaa, 0xa2, 0x71, 0x07,
	0xf4, 0x93, 0x7c, 0xeb, 0xec, 0x61, 0x13, 0x5a, 0x53, 0xb6, 0x5a, 0x39, 0xc8, 0x7b, 0x05, 0x76,
	0xa3, 0x22, 0x11, 0x71, 0x3e, 0x7b, 0xe3, 0xec, 0x29, 0x61, 0xe6, 0x20, 0x21, 0x8c, 0x27, 0x6f,
	0x1c, 0x4d, 0x08, 0x67, 0x93, 0x0b, 0x47, 0xf7, 0x7e, 0x2f, 0x52, 0xca, 0x12, 0x2c, 0x30, 0xde,
	0x8e, 0x2f, 0xc7, 0x33, 0x67, 0x0f, 0x03, 0xb4, 0x2f, 0x47, 0xe4, 0xe2, 0x54, 0x9c, 0x3a, 0x00,
	0x6b, 0x3a, 0x9b, 0x5c, 0xcd, 0xdf, 0x4e, 0xa6, 0x53, 0x47, 0xc3, 0x8f, 0xe0, 0xb0, 0x52, 0xe7,
	0x2a, 0x5e, 0xc7, 0x87, 0x60, 0xcf, 0x46, 0x17, 0xa7, 0xf3, 0x2b, 0x32, 0x39, 0x1b, 0xcf, 0x9c,
	0x16, 0x7e, 0x02, 0x9f, 0x35, 0x0c, 0x45, 0x9c, 0x21, 0xe2, 0xa4, 0x38, 0xbf, 0x1c, 0x5d, 0x9c,
	0x12, 0xa7, 0xed, 0x51, 0xb0, 0xd5, 0x9b, 0x38, 0xe5, 0x79, 0x86, 0x5d, 0xe8, 0xc8, 0x96, 0x8c,
	0x4b, 0xcc, 0x4b, 0x15, 0xf7, 0xa1, 0x2d, 0x07, 0x2d, 0x73, 0x35, 0x39, 0xad, 0xa6, 0xbf, 0xf1,
	0x67, 0xc2, 0x40, 0x0a, 0xbb, 0xa0, 0x5b, 0x26, 0xb3, 0xc8, 0x11, 0xb0, 0x48, 0xa1, 0x79, 0x7d,
	0x00, 0x19, 0xa8, 0x68, 0x55, 0xc2, 0x8c, 0x6a, 0x98, 0xbd, 0x1f, 0xc0, 0x96, 0x11, 0xd9, 0x83,
	0x21, 0x62, 0xee, 0x56, 0xd1, 0x4d, 0xa4, 0xf8, 0xaf, 0x13, 0xa5, 0x78, 0x01, 0x38, 0x8a, 0xb9,
	0x8d, 0x0b, 0x9e, 0xdd, 0xe5, 0xed, 0x41, 0x59, 0xe7, 0x27, 0xb3, 0xf6, 0x2f, 0x04, 0x86, 0xcc,
	0xf0, 0x11, 0x19, 0x9e, 0x83, 0x71, 0x43, 0x97, 0x2c, 0x95, 0x19, 0xba, 0xc3, 0x6e, 0x79, 0x95,
	0x7f, 0x29, 0xac, 0x44, 0x39, 0x6b, 0xca, 0xe8, 0x0f, 0x51, 0xa6, 0x75, 0x8f, 0x32, 0xbb, 0xa8,
	0xf0, 0x12, 0x20, 0x48, 0x19, 0xe5, 0x2c, 0x9c, 0x53, 0x2e, 0x99, 0xa0, 0x4a, 0x16, 0x13, 0x97,
	0x71, 0x7a, 0xb3, 0x26, 0x56, 0xe1, 0x1f, 0x71, 0xef, 0x25, 0x18, 0xb2, 0x04, 0x6c, 0x43, 0xe7,
	0x97, 0x78, 0x19, 0x27, 0xbf, 0xc5, 0xce, 0x9e, 0x98, 0xaf, 0x93, 0x7c, 0xcb, 0x52, 0x07, 0x89,
	0xf9, 0x12, 0x43, 0xcb, 0x52, 0x47, 0xf3, 0x8e, 0xa0, 0xad, 0xba, 0xdf, 0xc0, 0x18, 0xed, 0xc6,
	0x58, 0x60, 0x79, 0x9d, 0x27, 0xfc, 0x3f, 0xb0, 0xac, 0x20, 0x69, 0xc4, 0xed, 0x80, 0xa4, 0xf6,
	0x7e, 0x0a, 0x24, 0x7f, 0x22, 0x30, 0x64, 0x06, 0xd1, 0x46, 0x9a, 0x2d, 0xaf, 0x64, 0x7f, 0x91,
	0x6a, 0x63, 0xa9, 0x0b, 0x4a, 0xd3, 0x6c, 0x39, 0xaf, 0xda, 0xac, 0x3e, 0x59, 0x36, 0xcd, 0x96,
	0xd7, 0x65, 0xa7, 0xbf, 0x00, 0x6b, 0x11, 0x85, 0xf3, 0x26, 0x3e, 0xe6, 0x22, 0x0a, 0xab, 0xf3,
	0xc2, 0x79, 0x0f, 0x26, 0x7b, 0x11, 0x85, 0xd7, 0xff, 0x1b, 0x52, 0x3f, 0x83, 0x55, 0xd9, 0x05,
	0xfb, 0x32, 0x16, 0x24, 0x71, 0x58, 0xee, 0xc5, 0x52, 0xad, 0xf7, 0xa5, 0xd6, 0xd8, 0x97, 0xc3,
	0x7f, 0x34, 0x30, 0x4f, 0x8b, 0x45, 0x8b, 0xbf, 0x01, 0x38, 0x67, 0xbc, 0x5c, 0x2f, 0xf7, 0xd7,
	0x55, 0x0f, 0x6a, 0x03, 0x7e, 0x0d, 0x07, 0x77, 0x16, 0x1e, 0x7e, 0xe2, 0x6f, 0xfc, 0x8f, 0x57,
	0x60, 0xf3, 0xcc, 0x31, 0xc2, 0xcf, 0xc1, 0xbc, 0xca, 0xb9, 0x5a, 0x0b, 0x66, 0xf9, 0x31, 0xed,
	0x75, 0x4b, 0xa9, 0xf8, 0x82, 0x1c, 0xc1, 0xbe, 0xca, 0x24, 0x8d, 0xd9, 0xc3, 0x91, 0x03, 0x84,
	0x5f, 0x80, 0x75, 0xce, 0x78, 0x31, 0x7c, 0x15, 0x7b, 0xd4, 0x57, 0xa0, 0x67, 0x55, 0x3a, 0xfe,
	0xb6, 0xcc, 0x59, 0xe8, 0x8f, 0xaa, 0x72, 0x6b, 0x66, 0xf7, 0xaa, 0x61, 0x3d, 0x46, 0xf8, 0x19,
	0x98, 0xe7, 0x8c, 0xab, 0x09, 0xb9, 0x3b, 0x6d, 0x32, 0x4c, 0x39, 0xaa, 0xac, 0x52, 0x6d, 0x66,
	0xdd, 0x15, 0x7e, 0x8c, 0x16, 0x6d, 0xf9, 0x5f, 0xe6, 0xbb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x19, 0xc0, 0x53, 0x7d, 0xdd, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExchangeClient is the client API for Exchange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExchangeClient interface {
	GetAccount(ctx context.Context, in *AccountQuery, opts ...grpc.CallOption) (*Account, error)
	StreamAccount(ctx context.Context, in *StreamAccountQuery, opts ...grpc.CallOption) (Exchange_StreamAccountClient, error)
	PutOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OrderStatus, error)
	StreamOrders(ctx context.Context, opts ...grpc.CallOption) (Exchange_StreamOrdersClient, error)
	GetTrades(ctx context.Context, in *TradesQuery, opts ...grpc.CallOption) (*Trades, error)
	StreamTrades(ctx context.Context, in *StreamTradeQuery, opts ...grpc.CallOption) (Exchange_StreamTradesClient, error)
	GetQuote(ctx context.Context, in *QuoteQuery, opts ...grpc.CallOption) (*Quote, error)
	StreamQuotes(ctx context.Context, in *StreamQuoteQuery, opts ...grpc.CallOption) (Exchange_StreamQuotesClient, error)
}

type exchangeClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeClient(cc grpc.ClientConnInterface) ExchangeClient {
	return &exchangeClient{cc}
}

func (c *exchangeClient) GetAccount(ctx context.Context, in *AccountQuery, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/x.Exchange/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeClient) StreamAccount(ctx context.Context, in *StreamAccountQuery, opts ...grpc.CallOption) (Exchange_StreamAccountClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Exchange_serviceDesc.Streams[0], "/x.Exchange/StreamAccount", opts...)
	if err != nil {
		return nil, err
	}
	x := &exchangeStreamAccountClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Exchange_StreamAccountClient interface {
	Recv() (*Account, error)
	grpc.ClientStream
}

type exchangeStreamAccountClient struct {
	grpc.ClientStream
}

func (x *exchangeStreamAccountClient) Recv() (*Account, error) {
	m := new(Account)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exchangeClient) PutOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OrderStatus, error) {
	out := new(OrderStatus)
	err := c.cc.Invoke(ctx, "/x.Exchange/PutOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeClient) StreamOrders(ctx context.Context, opts ...grpc.CallOption) (Exchange_StreamOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Exchange_serviceDesc.Streams[1], "/x.Exchange/StreamOrders", opts...)
	if err != nil {
		return nil, err
	}
	x := &exchangeStreamOrdersClient{stream}
	return x, nil
}

type Exchange_StreamOrdersClient interface {
	Send(*Order) error
	CloseAndRecv() (*OrderStatus, error)
	grpc.ClientStream
}

type exchangeStreamOrdersClient struct {
	grpc.ClientStream
}

func (x *exchangeStreamOrdersClient) Send(m *Order) error {
	return x.ClientStream.SendMsg(m)
}

func (x *exchangeStreamOrdersClient) CloseAndRecv() (*OrderStatus, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(OrderStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exchangeClient) GetTrades(ctx context.Context, in *TradesQuery, opts ...grpc.CallOption) (*Trades, error) {
	out := new(Trades)
	err := c.cc.Invoke(ctx, "/x.Exchange/GetTrades", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeClient) StreamTrades(ctx context.Context, in *StreamTradeQuery, opts ...grpc.CallOption) (Exchange_StreamTradesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Exchange_serviceDesc.Streams[2], "/x.Exchange/StreamTrades", opts...)
	if err != nil {
		return nil, err
	}
	x := &exchangeStreamTradesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Exchange_StreamTradesClient interface {
	Recv() (*Trade, error)
	grpc.ClientStream
}

type exchangeStreamTradesClient struct {
	grpc.ClientStream
}

func (x *exchangeStreamTradesClient) Recv() (*Trade, error) {
	m := new(Trade)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exchangeClient) GetQuote(ctx context.Context, in *QuoteQuery, opts ...grpc.CallOption) (*Quote, error) {
	out := new(Quote)
	err := c.cc.Invoke(ctx, "/x.Exchange/GetQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeClient) StreamQuotes(ctx context.Context, in *StreamQuoteQuery, opts ...grpc.CallOption) (Exchange_StreamQuotesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Exchange_serviceDesc.Streams[3], "/x.Exchange/StreamQuotes", opts...)
	if err != nil {
		return nil, err
	}
	x := &exchangeStreamQuotesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Exchange_StreamQuotesClient interface {
	Recv() (*Quote, error)
	grpc.ClientStream
}

type exchangeStreamQuotesClient struct {
	grpc.ClientStream
}

func (x *exchangeStreamQuotesClient) Recv() (*Quote, error) {
	m := new(Quote)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExchangeServer is the server API for Exchange service.
type ExchangeServer interface {
	GetAccount(context.Context, *AccountQuery) (*Account, error)
	StreamAccount(*StreamAccountQuery, Exchange_StreamAccountServer) error
	PutOrder(context.Context, *Order) (*OrderStatus, error)
	StreamOrders(Exchange_StreamOrdersServer) error
	GetTrades(context.Context, *TradesQuery) (*Trades, error)
	StreamTrades(*StreamTradeQuery, Exchange_StreamTradesServer) error
	GetQuote(context.Context, *QuoteQuery) (*Quote, error)
	StreamQuotes(*StreamQuoteQuery, Exchange_StreamQuotesServer) error
}

// UnimplementedExchangeServer can be embedded to have forward compatible implementations.
type UnimplementedExchangeServer struct {
}

func (*UnimplementedExchangeServer) GetAccount(ctx context.Context, req *AccountQuery) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (*UnimplementedExchangeServer) StreamAccount(req *StreamAccountQuery, srv Exchange_StreamAccountServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAccount not implemented")
}
func (*UnimplementedExchangeServer) PutOrder(ctx context.Context, req *Order) (*OrderStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutOrder not implemented")
}
func (*UnimplementedExchangeServer) StreamOrders(srv Exchange_StreamOrdersServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamOrders not implemented")
}
func (*UnimplementedExchangeServer) GetTrades(ctx context.Context, req *TradesQuery) (*Trades, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrades not implemented")
}
func (*UnimplementedExchangeServer) StreamTrades(req *StreamTradeQuery, srv Exchange_StreamTradesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTrades not implemented")
}
func (*UnimplementedExchangeServer) GetQuote(ctx context.Context, req *QuoteQuery) (*Quote, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuote not implemented")
}
func (*UnimplementedExchangeServer) StreamQuotes(req *StreamQuoteQuery, srv Exchange_StreamQuotesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamQuotes not implemented")
}

func RegisterExchangeServer(s *grpc.Server, srv ExchangeServer) {
	s.RegisterService(&_Exchange_serviceDesc, srv)
}

func _Exchange_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/x.Exchange/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServer).GetAccount(ctx, req.(*AccountQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exchange_StreamAccount_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAccountQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExchangeServer).StreamAccount(m, &exchangeStreamAccountServer{stream})
}

type Exchange_StreamAccountServer interface {
	Send(*Account) error
	grpc.ServerStream
}

type exchangeStreamAccountServer struct {
	grpc.ServerStream
}

func (x *exchangeStreamAccountServer) Send(m *Account) error {
	return x.ServerStream.SendMsg(m)
}

func _Exchange_PutOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServer).PutOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/x.Exchange/PutOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServer).PutOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exchange_StreamOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExchangeServer).StreamOrders(&exchangeStreamOrdersServer{stream})
}

type Exchange_StreamOrdersServer interface {
	SendAndClose(*OrderStatus) error
	Recv() (*Order, error)
	grpc.ServerStream
}

type exchangeStreamOrdersServer struct {
	grpc.ServerStream
}

func (x *exchangeStreamOrdersServer) SendAndClose(m *OrderStatus) error {
	return x.ServerStream.SendMsg(m)
}

func (x *exchangeStreamOrdersServer) Recv() (*Order, error) {
	m := new(Order)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Exchange_GetTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradesQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServer).GetTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/x.Exchange/GetTrades",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServer).GetTrades(ctx, req.(*TradesQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exchange_StreamTrades_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTradeQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExchangeServer).StreamTrades(m, &exchangeStreamTradesServer{stream})
}

type Exchange_StreamTradesServer interface {
	Send(*Trade) error
	grpc.ServerStream
}

type exchangeStreamTradesServer struct {
	grpc.ServerStream
}

func (x *exchangeStreamTradesServer) Send(m *Trade) error {
	return x.ServerStream.SendMsg(m)
}

func _Exchange_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/x.Exchange/GetQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServer).GetQuote(ctx, req.(*QuoteQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exchange_StreamQuotes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamQuoteQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExchangeServer).StreamQuotes(m, &exchangeStreamQuotesServer{stream})
}

type Exchange_StreamQuotesServer interface {
	Send(*Quote) error
	grpc.ServerStream
}

type exchangeStreamQuotesServer struct {
	grpc.ServerStream
}

func (x *exchangeStreamQuotesServer) Send(m *Quote) error {
	return x.ServerStream.SendMsg(m)
}

var _Exchange_serviceDesc = grpc.ServiceDesc{
	ServiceName: "x.Exchange",
	HandlerType: (*ExchangeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _Exchange_GetAccount_Handler,
		},
		{
			MethodName: "PutOrder",
			Handler:    _Exchange_PutOrder_Handler,
		},
		{
			MethodName: "GetTrades",
			Handler:    _Exchange_GetTrades_Handler,
		},
		{
			MethodName: "GetQuote",
			Handler:    _Exchange_GetQuote_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAccount",
			Handler:       _Exchange_StreamAccount_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamOrders",
			Handler:       _Exchange_StreamOrders_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamTrades",
			Handler:       _Exchange_StreamTrades_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamQuotes",
			Handler:       _Exchange_StreamQuotes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "exchange.proto",
}
